//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace FamilyBooks.Common.User
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class User
	{
		public virtual object ID
		{
			get;
			set;
		}

		public virtual object Name
		{
			get;
			set;
		}

	}
}

